# Generated by Django 2.2.1 on 2019-06-01 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsKey',
            fields=[
                ('key_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('key_secret', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
            ],
        ),
    ]
