# Generated by Django 2.2.1 on 2019-06-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sec_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecGroup',
            fields=[
                ('GroupId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_group.SecGroup')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
