# Generated by Django 2.2.1 on 2019-06-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_group', '0002_secgroup_secgrouppermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secgrouppermission',
            old_name='GroupId',
            new_name='GroupName',
        ),
    ]
