# Generated by Django 2.2.1 on 2019-06-02 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sec_group', '0003_auto_20190602_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awskey',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 57, 50, 715513, tzinfo=utc)),
        ),
    ]
